---
run:
  timeout: "240s"

output:
  formats:
    - format: "colored-line-number"

linters:
  enable:
    - gocyclo
    - unconvert
    - goimports
    - unused
    - misspell
    - nakedret
    - errcheck
    - revive
    - ineffassign
    - goconst
    - govet
    - unparam
    - gofumpt
    - prealloc
    - mnd
    - gocritic


linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true

issues:
  exclude-use-default: false
